### ISSUE TITLE
Command two devices with one serial port

### ISSUE THREAD

**Issue by pierrotm777** [jfjlaros/serialMux#1]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
No

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
I have only one serial port usable on by actual pro mini board .
Actually, i command one DFPlayer with the serial port.
Is it possible to command two player with one serial port?

Thanks,

Pierre

**Comment by jfjlaros** [comment]
If I understand you correctly, you want to connect two physical devices using one serial port?

This library supports multiple (virtual) serial connections to the *same* device, so I do not think it will be of any help in this case.

**Comment by pierrotm777** [comment]
Thanks you for your quick answer.
Virtual only.
Pierre

**Comment by jfjlaros** [comment]
>  Virtual only.

I am not sure what you mean by this.

**Comment by pierrotm777** [comment]
Exactly what you said me :-)
"This library supports multiple (virtual) serial"

**Comment by jfjlaros** [comment]
Okay, I will close this issue then. Good luck with your project.
